name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v0 # Replace 'v0' with the actual version number

    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account --key-file="${{ secrets.GCP_SA_KEY }}"

    - name: Deploy to Firebase
      run: firebase deploy --only hosting --project losjoses
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
