name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Use the Node.js version compatible with your project

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate Firebase CLI with Service Account
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" | base64 --decode > gcp-sa-key.json
        gcloud auth activate-service-account --key-file=gcp-sa-key.json

    - name: Deploy to Firebase
      run: firebase deploy --only hosting --project losjoses
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-sa-key.json
