name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Use the Node.js version compatible with your project

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate Firebase CLI with Service Account
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 --decode > ./gcp-sa-key.json
        firebase use --add --token "$FIREBASE_TOKEN" # Use the Firebase token if you're not using a service account
        firebase functions:config:set google_application_credentials=./gcp-sa-key.json # This step is usually not necessary for Firebase Hosting, but can be used for Firebase Functions

    - name: Deploy to Firebase
      run: firebase deploy --only hosting --project losjoses --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
