name: Deploy to Firebase Hosting

# This workflow is triggered on pushes to the main branch.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Set this to your node version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build # Replace with your build command

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
