name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Google Cloud Credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: losjoses
        export_default_credentials: true

    - name: Deploy to Firebase
      run: firebase deploy --only hosting --project losjoses
